### ISSUE TITLE
Automação de contribuidores

### ISSUE THREAD

**Issue by 1cadumagalhaes** [datacareer-guide/datacareer-guide.github.io#3]
**Is your feature request related to a problem? Please describe.**
Acrescentar programáticamente os contribuidores no arquivo CONTRIBUTORS.md.

**Describe the solution you'd like**
[Github Workflow - Add Contributors](https://github.com/BobAnkh/add-contributors)

**Comment by ViniViniAntunes** [comment]
Abri o PR https://github.com/datacareer-guide/datacareer-guide.github.io/pull/9 para resolver essa issue.
